links/urls.py
from django.conf.urls import patterns, url

from links import views

urlpatterns = patterns('',
    url(r'^view/(?P<hash>[a-zA-Z0-9]+)/$', views.reverse_map_link, name='view'),
)

reviewit/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic import TemplateView

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',

    url(
        r'^', 
        include(
            'reviews.urls', 
            namespace="reviews"
        )
    ),

    url(
        r'^accounts/', 
        include(
            'allauth.urls', 
            namespace="allauth"
        )
    ),

    url(
        r'^comment/', 
        include(
            'comments.urls', 
            namespace="comments"
        )
    ),

    url(
        r'^link/', 
        include(
            'links.urls', 
            namespace="links"
        )
    ),

    url(
        r'^invite/', 
        include(
            'invites.urls', 
            namespace="invites"
        )
    ),

    url(
        r'^admin/', 
        include(
            admin.site.urls
        )
    ),

    url(
        r'^terms/', 
        TemplateView.as_view(template_name="terms.html"),
        name='terms'
    ),

    url(
        r'^privacy/', 
        TemplateView.as_view(template_name="privacy.html"),
        name='privacy'
    ),

    url(
        r'^about/', 
        TemplateView.as_view(template_name="about.html"),
        name='about'
    ),

    url(
        r'^careers/', 
        TemplateView.as_view(template_name="career.html"),
        name='careers'
    ),
)

reviews/urls.py
from django.conf.urls import patterns, url
from rest_framework.urlpatterns import format_suffix_patterns

from reviews import views

urlpatterns = patterns('',
    
    url(
    	r'^$', 
    	views.index, 
    	name='index'
    ),

    url(
    	r'^ask/$', 
    	views.ask, 
    	name='ask'
    ),

    url(
    	r'^view/(?P<review_id>\d+)/$', 
    	views.view, 
    	name='view'
    ),
    
    url(
    	r'^list/$', 
    	views.list, 
    	name='list'
    ),

    url(
    	r'^list/(?P<username>[a-zA-Z0-9]+)/$', 
    	views.list, 
    	name='browse'
    ),

    url(
        r'^search/$', 
        views.search, 
        name='search'
    ),

    url(
        r'^feedback/$', 
        views.feedback, 
        name='feedback'
    ),

    url(
        r'^(?P<page>[-\w]+.html)/$',
        views.angular_views,
        name='angular_views'
    ),
)

urlpatterns = format_suffix_patterns(urlpatterns)

reviews/models.py
from django.contrib.auth.models import User
from django.db import models

from .managers import ReviewManager
from links.models import Link

class Review(models.Model):
    title = models.CharField(max_length=2000)
    link = models.ForeignKey(Link)
    query = models.CharField(max_length=10000)
    date = models.DateTimeField()
    reviewee = models.ForeignKey(User, related_name='reviewee') # user.reviewee.all()
    reviewers = models.ManyToManyField(User, related_name='reviewers') # user.reviewers.all()
    status = models.IntegerField(default=0)
    objects = ReviewManager()

    def __unicode__(self):
        return self.title

    def is_reviewee(self, user):
    	# returns True if the user is the reviewee
    	return self.reviewee == user

reviews/forms.py
from django import forms

from .models import Review

class ReviewForm(forms.Form):
	title = forms.CharField(required=True, label='title')
	link = forms.URLField(required=True, label='product link')
	query = forms.CharField(required=True, widget=forms.Textarea, label='product queries')

	class Meta:
		model = Review 
		fields = ("title", "link", "query")

reviews/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.core.urlresolvers import reverse
from django.views.decorators.csrf import csrf_protect
from django.contrib.auth.decorators import login_required
from django.contrib import auth
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist, MultipleObjectsReturned

from links.models import Link
from invites.models import Invite
from comments.models import Comment
from .models import Review

from allauth.forms import AuthenticateForm
from comments.forms import CommentForm
from invites.forms import InviteForm
from .forms import ReviewForm

# Rest Framework specific imports
from rest_framework import status
from rest_framework.decorators import api_view, renderer_classes
from rest_framework.response import Response
from rest_framework.renderers import TemplateHTMLRenderer
from .serializers import ReviewSerializer

def index(request):
    return render(request, 'reviewsManager.html')

def angular_views(request, page):
    return render(request, page)

@csrf_protect
@login_required
def ask(request):
    """
    Creates a review and saves
    """
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            title = cd['title']
            query = cd['query']
            link  = cd['link']
            
            link_obj = Link.objects.create_link(link)
            review = Review.objects.create_review(title, link_obj, query, request.user)

            return redirect(
                reverse(
                    'reviews:view', 
                    args=(
                        review.id,
                    )
                )
            )
    else:
        form = ReviewForm()

    response = {'form': form}
    return render(request, 'ask.html', response)

@csrf_protect
def feedback(request):
    """
    Feedback for the app
    """
    admin = User.objects.get(username='admin')

    title = 'review reviewit app'
    link = Link.objects.create_link('http://reviewit.co.in')
    query = 'Please provide feedback on the reviewit app'

    try:
        review = Review.objects.get(reviewee=admin)
    except MultipleObjectsReturned:
        review = Review.objects.filter(reviewee=admin)[0]
    except ObjectDoesNotExist.DoesNotExist:
        review = Review.objects.create_review(title, link, query, admin)
    
    return redirect(reverse('reviews:view', args=(review.id, )))

@api_view(['GET'])
def view(request, review_id):
    review = get_object_or_404(Review, pk=review_id)

    serializer = ReviewSerializer(review)
    return Response(serializer.data)

@api_view(['GET'])
def list(request, username='anonymous', format=None):
    user = get_object_or_404(User, username=username)
    
    if request.user.is_anonymous() or username == 'anonymous':
        request.session['next_page'] = reverse('reviews:list')
        reviews = Review.objects.all().order_by('-date')
    else:
        reviews = Review.objects.get_all_reviews(user=user).order_by('-date')
    
    serializer = ReviewSerializer(reviews, many=True)
    return Response(serializer.data)


def search(request):
    """
    Search for reviews matching query_string
    """
    query_string = ''
    found_entries = Review.objects.all()

    if ('q' in request.GET) and request.GET['q'].strip():
        query_string = request.GET['q']
        
        found_entries = Review.objects.search_all(query_string).order_by('-date')

    response = {
        'query_string': query_string,
        'reviews': found_entries
    }

    return render(request, 'list.html', response)

reviews/templates/ask.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block page-title %}
start a review
{% endblock %}

{% block alpha %}
<div class="formContent" style="margin: 5px 0;">
  <form action="{% url 'reviews:ask' %}" method="post" id="ask_form">
    {% csrf_token %}
    {{ form.as_p }}
    <button class="pure-button" style="margin:10px 0;">reviewit</button>
  </form>
</div>
{% endblock %}

{% block sidebar-title %}
<div class="h1" style="text-align:center;">
reviewers
</div>
<div id="block" class="divider" style="margin-bottom:10px;">
</div>
{% endblock %}

{% block sidebar-content %}
<div class="formContent" style="margin-top: 5px;width:65%;margin:0 auto;">
  <button class="pure-button pure-button-disabled">reviewit to add people</button>
</div>
{% endblock %}

reviews/templates/detail.html
{% verbatim %}
<div class="review-item">
  <a href="{{ review.link.link }}" target="_blank">{{ review.title }}</a>
  <div>
    {{ review.query }}
  </div>
  <div>
    <strong>{{ review.reviewee.username }}</strong>
    <span class="bullet">•</span>
    <span class="timestamp">
      {{ review.date }}
    </span>
  </div>
</div>
{% endverbatim %}

reviews/templates/index.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block main-content %}
<div class="column grid_8 alpha">
  <img src="{% static 'images/Banner.jpg' %}">
</div>
<div class="column grid_8" style="width:30%;padding-top:40px">
  <div class="h1" style="text-align:right;">
    how this works
  </div>
  <div id="block" class="divider" style="margin-bottom:10px;">
  </div>
  <ul style="direction:rtl;">
    <li>
      create a product review
    </li>
    <li>
      add friends to the review
    </li>
    <li>
      submit and wait for feedback
    </li>
    <li>
      D-:
    </li>
  </ul>
</div>
{% endblock %}

{% block sidebar-title %}
{% endblock %}

{% block sidebar-content %}
<div class="block heading" data-type="heading" data-title="heading" data-id="3">
  <div class="formContent" style="margin-top: 5px;width:65%;margin:0 auto;">
    <form action="{% url 'allauth:login' %}" method="post" id='login_form'>
      {% csrf_token %}
      {{ form.as_p }}
        <div>
          <button class="pure-button">login</button>
        </div>
        <div class="h1" style="font-size:20px;">
          or
          <a href="{% url 'allauth:register' %}" target="_self">
           register
          </a>
        </div>
    </form>
  </div>
  <div id="block" class="divider" style="margin:30px 0;">
  </div>          
  <div class="h1" style="text-align:center;font-size:20px;font-style:italic;">
    <a href="{% url 'reviews:list' %}" target="_self">
      continue as guest
    </a>
  </div>
</div>
{% endblock %}

reviews/templates/invite_email.html
<p>
Hello, <br><br>

<strong>{{ username }}</strong> has added you to <a href="{{ link }}" target="_blank">{{ title }}</a><br><br>

Please click on the above link to give your reviews.<br><br>

Regards,<br>
<strong>Reviewit Team</strong>
</p>

reviews/templates/list.html
{% verbatim %}
<ul>
    <li ng-repeat='review in reviews'>
        <div>
            <a href='#/view/{{ review.id }}'>{{ review.title }}</a>
            <div class="review-author">
                <span class="text">posted by {{ review.reviewee.username }}</span>
                <span class="timestamp"> {{ review.date }}</span>
            </div>
        </div>
    </li>
</ul>
{% endverbatim %}

reviews/templates/reviewsManager.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block page-title %}
<h3>Reviews</h3>
{% endblock %}

{% block alpha %}
{% verbatim %}
<div class="reviews-List" ng-app="reviewsApp">
    <div ng-view></div>
</div>
{% endverbatim %}
{% endblock %}

{% block sidebar-title %}
{% endblock %}

reviews/templates/view.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load humanize %}

{% block page-title %}
<a href="{{ review.link.link }}" target="_blank">{{ review.title }}</a>
{% endblock %}

{% block alpha %}
<div class="item_review">
  <div id="query" class="item">
    {{ review.query|safe }}
  </div>
  <div class="item">
    <strong>{{ review.reviewee.username }}</strong>
    <span class="bullet">•</span>
    <span class="timestamp">
      {{ review.date|naturaltime }}
    </span>
  </div>
</div>

<div class="h1" style="text-align:justify;margin-top:40px;">
  reviews (<span id="comment_count">{{ comments.count }}</span>)
</div>
<div id="block" class="divider" style="margin-bottom:10px;">
</div>
<div>
  <ul id="comments_list">
    {% for comment in comments %}
    <li class="item_comment">
      <strong>
        {{ comment.user.username }}
      </strong>
      <span class="bullet">•</span>
      <span class="timestamp">{{ comment.date|naturaltime }}</span>
      <br>
      {{ comment.detail|safe }}
    </li>
    {% endfor %}
  </ul>
</div>
<div class="formContent" style="margin: 5px 0;">
  <form action="{% url 'comments:add' review.id %}" method="post" id="comment_form">
    {% csrf_token %}
    {{ comment_form.as_p }}
    <button class="pure-button" style="margin:10px 0;">submit</button>
  </form>
</div>
{% endblock %}

{% block sidebar-title %}
<div class="h1" style="text-align:center;">
  reviewers
</div>
<div id="block" class="divider" style="margin-bottom:10px;">
</div>
{% endblock %}

{% block sidebar-content %}
{% if is_reviewee %}
<div class="formContent" style="margin-top: 5px;width:65%;margin:0 auto;">
  <form action="{% url 'invites:add' review.id %}" method="post" id="add_friend_form">
    {% csrf_token %}
    {{ invite_form.as_p }}
    <button class="pure-button">add</button>
  </form>
</div>
{% endif %}
<div>
  <ul id="reviewers_list">
    {% for reviewer in reviewers %}
    <li class="item_reviewer">
      {{ reviewer.username }}
    </li>
    {% endfor %}
  </ul>
</div>
{% if is_reviewee %}
<div class="h1" style="text-align:center;font-size:22px;">
  invitees
</div>
<div id="block" class="divider" style="margin-bottom:10px;">
</div>
<div>
  <ul id="invite_list">
    {% for invitee in invitees %}
    <li class="item_invite">
      {{ invitee.email }}
    </li>
    {% endfor %}
  </ul>
</div>
{% endif %}
{% endblock %}